# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under my_mlops_project/resources/*
# and my_mlops_project/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for my_mlops_project dev

on:
#  push:
#    branches:
#      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my_mlops_project

env:
  DATABRICKS_TOKEN: ${{ secrets.FORD_WORKSPACE_TOKEN }}


jobs:
  dev:
    concurrency: my_mlops_project-dev-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.236.0
      - name : echo data
        run: echo "$DATABRICKS_TOKEN"
      - name: Validate Bundle For dev
        id: validate
        run: |
          databricks bundle validate -t dev
      - name: Deploy Bundle to dev
        id: deploy
        run: |
          databricks bundle deploy -t dev
